"""Parser -> IR mapping, especially document authorship."""
import json

from ossbomer.core.parsers import parse_file


def _cdx(tmp_path, spec_version="1.6", **metadata):
    doc = {
        "$schema": f"http://cyclonedx.org/schema/bom-{spec_version}.schema.json",
        "bomFormat": "CycloneDX",
        "specVersion": spec_version,
        "serialNumber": "urn:uuid:509b1666-c1f2-4b3e-abd4-80bf52aa5ece",
        "version": 1,
        "metadata": {
            "timestamp": "2026-07-28T12:00:00Z",
            "component": {"bom-ref": "app@1", "name": "app", "type": "application",
                          "version": "1"},
            **metadata,
        },
        "components": [],
        "dependencies": [],
    }
    path = tmp_path / f"cdx-{spec_version}.json"
    path.write_text(json.dumps(doc))
    return parse_file(str(path))


# ---- CycloneDX document authorship -------------------------------------------
# `metadata.authors` is where CycloneDX puts human/organizational authorship, and
# it is entirely separate from `metadata.tools`. Reading only tools makes the
# "author of SBOM data" requirement unsatisfiable for any SBOM authored by a
# person rather than generated by a tool -- it is a MUST in ntia-min-elements,
# eu-cra-annex-vii, bsi-tr-03183-v2.1, cert-in-v2.0, fedramp-sbom,
# openchain-telco-v1.1 and aibom-v0.1.

def test_authors_populate_creators(tmp_path):
    sbom = _cdx(tmp_path, authors=[{"name": "Ada Lovelace", "email": "ada@example.org"}])
    assert sbom.document.creators == ["Ada Lovelace"]


def test_author_without_name_falls_back_to_email(tmp_path):
    sbom = _cdx(tmp_path, authors=[{"email": "ada@example.org"}])
    assert sbom.document.creators == ["ada@example.org"]


def test_manufacturer_counts_as_a_creator(tmp_path):
    sbom = _cdx(tmp_path, manufacturer={"name": "ACME Corp"})
    assert sbom.document.creators == ["ACME Corp"]


def test_legacy_manufacture_spelling_still_maps(tmp_path):
    """1.6 renamed `manufacture` to `manufacturer`; 1.3-1.5 docs use the old key."""
    sbom = _cdx(tmp_path, spec_version="1.5", manufacture={"name": "ACME Corp"})
    assert sbom.document.creators == ["ACME Corp"]


def test_tools_remain_creators_and_are_the_tool_subset(tmp_path):
    sbom = _cdx(
        tmp_path,
        authors=[{"name": "Ada Lovelace"}],
        tools={"components": [{"type": "application", "name": "gen", "version": "1"}]},
    )
    assert sbom.document.creators == ["Ada Lovelace", "gen"]
    # `tools` stays tool-only, so a rule can still distinguish the two.
    assert sbom.document.tools == ["gen"]


def test_legacy_tools_list_shape_still_maps(tmp_path):
    """<=1.4 encodes tools as a plain list rather than an object."""
    sbom = _cdx(tmp_path, spec_version="1.4", tools=[{"name": "gen", "version": "1"}])
    assert sbom.document.creators == ["gen"]
    assert sbom.document.tools == ["gen"]


def test_no_authorship_leaves_creators_empty(tmp_path):
    sbom = _cdx(tmp_path)
    assert sbom.document.creators == []
    assert sbom.document.tools == []


# ---- SPDX relationship mapping -----------------------------------------------

_MINI_SPDX = """SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: mini
DocumentNamespace: http://example.com/mini
Creator: Person: Ada Lovelace
Created: 2026-01-01T00:00:00Z

PackageName: alpha
SPDXID: SPDXRef-alpha
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageVersion: 1.0.0

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-alpha
Relationship: SPDXRef-alpha DEPENDS_ON NOASSERTION
"""


def test_noassertion_relationship_is_not_a_dependency_edge(tmp_path):
    """SPDX allows NOASSERTION where an element id would go.

    spdx-tools returns that as an SpdxNoAssertion object rather than a string.
    It states that no relationship is asserted, so it is not an edge and must
    not reach the dependency graph -- dependency_completeness compares those
    values against real component refs.
    """
    path = tmp_path / "mini.spdx"
    path.write_text(_MINI_SPDX)
    sbom = parse_file(str(path))

    for source, targets in sbom.dependencies.items():
        assert isinstance(source, str)
        for t in targets:
            assert isinstance(t, str), f"non-string ref {t!r} reached the graph"

    # The real edge survives; the NOASSERTION one does not.
    assert sbom.dependencies.get("SPDXRef-DOCUMENT") == ["SPDXRef-alpha"]
    assert sbom.dependencies.get("SPDXRef-alpha", []) == []
